name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: lein deps
    - name: build release
      run: lein release
    - uses: actions/upload-artifact@v2
      with:
        name: static-files
        path: ./resources/public
      
  deploy:
    
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: static-files    
    - name: Display structure of downloaded files
      run: ls -R
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: static-files
        remote_path: /var/www/html/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
